<a href="https://colab.research.google.com/github/catherinedrio/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using np.transpose() or using the T method

In [1]:
A = np.array([
              [1,2,5],
              [5,-1,0],
              [0,-3,3]
])
A

NameError: ignored

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [2,4,6,8],
    [1,2,3,4],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
D=np.array([
    [2,4,6,8],
    [1,2,3,4]        
])
D.shape

(2, 4)

In [ ]:
np.transpose(D).shape

(4, 2)

In [ ]:
D.T.shape

(4, 2)

In [ ]:
DT = D.T
DT

array([[2, 1],
       [4, 2],
       [6, 3],
       [8, 4]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [5,8],
    [1,2]
])
Y = np.array([
    [-1,6],
    [5,9]
])

In [ ]:
np.array_equiv(X, Y)

False

In [ ]:
np.dot(X,Y)

array([[ 35, 102],
       [  9,  24]])

In [ ]:
X.dot(Y)

array([[ 35, 102],
       [  9,  24]])

In [ ]:
X @ Y

array([[ 35, 102],
       [  9,  24]])

In [ ]:
np.matmul(X,Y)

array([[ 35, 102],
       [  9,  24]])

In [ ]:
K = np.array([
    [5,7,9],
    [1,2,3],
    [4,8,12]
])
J = np.array([
    [-2,0,5],
    [2,-4,6],
    [7,4,-3]
])

In [ ]:
np.array_equiv(K, J)

False

In [ ]:
K @ J

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [ ]:
K.dot(J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [ ]:
np.matmul(K, J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [ ]:
 np.dot(K, J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$Z = \begin{bmatrix}2&4&5&5\\5&-2&6&6\\0&1&2&2\end{bmatrix}, O = \begin{bmatrix}1&1\\3&3\\-1&4\end{bmatrix}, E = \begin{bmatrix}0&1&1&3\\1&1&2&5\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
Z = np.array([
    [2, 4, 5],
    [5, -2, 6],
    [0, 1, 2]
])
O = np.array([
    [1,1],
    [3,3],
    [-1,4]
])
E = np.array([
    [0,1,1,3],
    [1,1,2,5]
])
print(Z.shape)
print(O.shape)
print(E.shape)

(3, 3)
(3, 2)
(2, 4)


In [ ]:
O @ E

array([[ 1,  2,  3,  8],
       [ 3,  6,  9, 24],
       [ 4,  3,  7, 17]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
E = A + (B + C)
E

array([[ 8,  4,  7],
       [ 8,  7, 11],
       [ 3,  5, 10]])

In [ ]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [ ]:
E = (B + C) @ A
E

array([[29, 26, 13],
       [30, 28, 16],
       [31, 33, 15]])

In [ ]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [ ]:
np.array_equal(E, X)

False

In [ ]:
np.array_equiv(E, F)

True

In [ ]:
A @ E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [2,3],
    [1,3]
])
np.linalg.det(A)

NameError: ignored

In [ ]:
B = np.array([
              [2, -3, 4],
              [1, 6 ,0],
              [-3, 6, 9]
])
np.linalg.det(B)

230.99999999999994

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,-3,4,6],
    [1,6,0,3],
    [-3,6,9,2],
    [1,2,3,4]
])
np.linalg.det(B)

-88.00000000000003

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [3,6],
    [-4, 8]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [3, 6, 9],
              [-4, 8, 12],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[ 0.16666667, -0.125     , -0.        ],
       [-0.66666667,  0.0625    ,  0.75      ],
       [ 0.5       , -0.        , -0.5       ]])

In [ ]:
P @ Q

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 0.0000000e+00, 1.0000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
Z = np.array ([
    [1,2,3,4],
    [10,20,30,40],
    [6,8,10,12],
    [3,6,9,15]           
])
O = np.array ([
    [2,4,6,8],
    [0,9,2,6],
    [0,0,6,9],
    [3,2,0,1]           
])
E = np.array ([
    [4,8,12,16],
    [5,10,15,20],
    [9,18,27,36],
    [7,14,21,28]           
])

In [ ]:
A = Z.dot(O)
B = O.dot(E)
C = E.dot(Z)
D = Z.dot(A)
F = C.dot(E)
G = Z + O
H = E + Z
I = F + A

In [ ]:
print('PROPERTY 1')
{np.array_equiv(Z, O)}
print('AB=BA')
print('Matrix AB:')
print(np.matmul(A,B))
print('Matrix BA:')
print(np.matmul(B,A))
print('APPROVED!')

PROPERTY 1
AB=BA
Matrix AB:
[[  9837  19674  29511  39348]
 [ 98370 196740 295110 393480]
 [ 38070  76140 114210 152280]
 [ 31470  62940  94410 125880]]
Matrix BA:
[[ 88596 189612 173880 315882]
 [ 67410 144270 132300 240345]
 [ 75114 160758 147420 267813]
 [ 18618  39846  36540  66381]]
APPROVED!


In [ ]:
print('PROPERTY 2')
{np.array_equiv(Z.dot(O),O.dot(E))}
print('A(BC)=(AB)C')
print('Matrix A(BC):')
print(np.matmul(Z,O))
print('Matrix (AB)C:')
print(np.matmul(O,E))
print('APPROVED!')

PROPERTY 2
A(BC)=(AB)C
Matrix A(BC):
[[ 14  30  28  51]
 [140 300 280 510]
 [ 48 120 112 198]
 [ 51  96  84 156]]
Matrix (AB)C:
[[138 276 414 552]
 [105 210 315 420]
 [117 234 351 468]
 [ 29  58  87 116]]
APPROVED!


In [ ]:
print('PROPERTY 3')
{np.array_equiv(C.dot(E),D)}
print('Matrix A(B+C)')
print(np.matmul(C,E))
print('Matrix (AB)+(AC):')
print(np.add(E,D))
print('APPROVED!')

PROPERTY 3
Matrix A(B+C)
[[ 12300  24600  36900  49200]
 [ 15375  30750  46125  61500]
 [ 27675  55350  83025 110700]
 [ 21525  43050  64575  86100]]
Matrix (AB)+(AC):
[[  646  1382  1272  2305]
 [ 6425 13750 12615 22910]
 [ 2305  4950  4563  8274]
 [ 2086  4424  4053  7363]]
APPROVED!


In [ ]:
print('PROPERTY 4')
{np.array_equiv(Z.dot(A),I)}
print('(B+C)A=(BA)+(CA)')
print('Matrix (B+C)A:')
print(np.matmul(Z,A))
print('Matrix (BA)+(CA):')
print(np.add(Z,I))
print('APPROVED!')

PROPERTY 4
(B+C)A=(BA)+(CA)
Matrix (B+C)A:
[[  642  1374  1260  2289]
 [ 6420 13740 12600 22890]
 [ 2296  4932  4536  8238]
 [ 2079  4410  4032  7335]]
Matrix (BA)+(CA):
[[ 12315  24632  36931  49255]
 [ 15525  31070  46435  62050]
 [ 27729  55478  83147 110910]
 [ 21579  43152  64668  86271]]
APPROVED!


In [ ]:
print('PROPERTY 5')
{np.array_equiv(E.dot(1),D)}
print('A(1)=A')
print('Matrix A(1):')
print(np.multiply(E,1))
print('Matrix A:')
print(D)
print('APPROVED!')

PROPERTY 5
A(1)=A
Matrix A(1):
[[ 4  8 12 16]
 [ 5 10 15 20]
 [ 9 18 27 36]
 [ 7 14 21 28]]
Matrix A:
[[  642  1374  1260  2289]
 [ 6420 13740 12600 22890]
 [ 2296  4932  4536  8238]
 [ 2079  4410  4032  7335]]
APPROVED!


In [ ]:
print('PROPERTY 6')
{np.array_equiv(O.dot(0),0)}
print('A(0)=0')
print('Matrix A(0):')
print(np.multiply(A,0))
print('APPROVED!')

PROPERTY 6
A(0)=0
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
APPROVED!


## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. 