<a href="https://colab.research.google.com/github/catherinedrio/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3: Matrices

We'll try to explore in greater dimensions now that you have a basic understanding of Python.

### Objectives
You will be able to:
1. Be familiar with matrices and how they relate to linear equations.
2. Basic matrix computations are performed.
3. Matrix equations can be programmed and translated using Python.

# Discussion

In [13]:
import numpy as np
## numpy - numerical python
import matplotlib.pyplot as plt
## matrix library
import scipy.linalg as la
%matplotlib inline

### Matrices

One of the most fundamental aspects of modern computing is the notation and use of matrices. Matrices are also useful representations of complicated equations or many interconnected equations, ranging from two-dimensional to hundreds of thousands of them.

Let's assume you have two variables, A and B, in your equation.

$$
A = \left\{
    \begin{array}\
        x + y \\
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\
        3x -2y -z \\
      -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\
        3w- x -2y +z \\
    \end{array}
\right. $$

As we can see, A is a system of two equations with two parameters. B, on the other hand, is a three-equation system with three parameters. They may be represented as matrices in the following way:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end
{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1
& 3 & -2\end{bmatrix}
$$

Assume you've already covered the fundamental format, types, and operations of matrices. We'll go ahead and do them in Python here.


### Declaring Matrices

We'll express a system of linear equations as a matrix, much like we did in our previous laboratory exercise. The elements of a matrix are the things or numbers in matrices. Matrixes have a list/array-like structure in which these items are grouped and ordered in rows and columns. These elements are indexed according to their location in relation to their rows and columns, exactly like arrays. The equation below can be used to express this. A is a matrix whose elements are indicated by the symbol aij. The number of rows in the matrix is denoted by i whereas the number of columns is denoted by j.

It's worth noting that a matrix's size is i x j.





$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{1,j-1)}\\
\vdots&\vdots&ddot&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We've previously gone over some of the different types of matrices as vectors, but in this lab assignment, we'll go over them again. Because you already know how to create vectors using form, dimensions, and size attributes, we'll use these features to study these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



# Categorizing Matrices

Matrixes can be classified in a variety of ways. One may be based on their form, while the other could be based on their element values. We'll do our best to get through them.

## According to shape

### Row and Column Matrices

In vector and matrix calculations, row and column matrices are frequent. They can also be used to represent the rows and columns of a larger vector space. A single column or row is used to depict row and column matrices. As a result, the form of row matrices is 1 x j, whereas the shape of column matrices is i x 1.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



### Square Matrices

Matrixes with the same row and column sizes are known as square matrices. If we can claim that a matrix is square, in order to find square matrices, we may change our matrix descriptor function.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



# According to element values

### Null Matrix


A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.


In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.



In [3]:
## Diagonal Matrix
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Upper Triangular Matrix


An upper triangular matrix is a matrix that has no values below the diagonal

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

# Practice

  1. Given the linear combination below, try to create a corresponding matrix representing it

:$$\theta = 5x + 3y = :$$

  2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra

## Addition

In [14]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [15]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

## Subtraction

In [16]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [17]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Element-wise Multiplication

In [18]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [19]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [21]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [22]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

# Activity

## Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix


Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
## Function area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
def mat_desc (matrix):
  if matrix.size > 0:
    if matrix.shape [0] == matrix.shape[1]:
      s = "Square."
    else:
      s = "Non-square."
    if np.all(matrix == np.identity(matrix.shape[0])):
      sp = "Identity Matrix."
    elif np.all(matrix == np.zeros(matrix.shape)):
      sp = "Zero Matrix."
    elif np.all(matrix == np.ones(matrix.shape)):
      sp = "Ones Matrix."
    else:
      sp = "None."
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\{matrix.ndim}\nSquare?: {s}\nSpecial Characteristics: {sp}')
  else:
    print('Matrix is Empty')

In [6]:
## Matrix declarations 
hi = np.array([ 
    [3,1,2,4], 
    [4,7,9,6], 
    [9,1,6,7]
])
one = np.array([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1], 
]) 
id = np.array([
    [1,0,0,0],
    [0,1,0,0], 
    [0,0,1,0],
    [0,0,0,1]
])

In [7]:
## Test Areas

In [9]:
mat_desc(hi)

Matrix:
[[3 1 2 4]
 [4 7 9 6]
 [9 1 6 7]]

Shape:	(3, 4)
Rank:\2
Square?: Non-square.
Special Characteristics: None.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if sys.path[0] == '':


In [10]:
mat_desc(one)

Matrix:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape:	(4, 5)
Rank:\2
Square?: Non-square.
Special Characteristics: Ones Matrix.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if sys.path[0] == '':


In [11]:
mat_desc(id)

Matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Shape:	(4, 4)
Rank:\2
Square?: Square.
Special Characteristics: Identity Matrix.


## Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should

  1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
  2. Returns the sum of the matrices.
  3. Returns the differen of the matrices.
  4. Returns the element-wise multiplication of the matrices.
  5. Returns the element-wise division of the matrices.


Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.



In [41]:
# Function Area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la 
%matplotlib inline
def mat_operations(matA,matB):
  op = input("Enter opration(+,-,*,/): ")
  if matA.shape == matB.shape:
    # proceed to operations
    if op == '+':
      return matA + matB
    elif op == '-':
      return matA - matB
    elif op == '*':
      return matA * matB
    elif op == '/':
      return matA/matB
    else:
      print("The matrices are viable but you have not inputted a correct operation.")
  else:
      print("Huhuhu.The matrices are not viable.")

In [39]:
#Matrix declarations 
A = np.array([ 
    [1,1,1,1], 
    [1,1,1,1], 
    [1,1,1,1],
    [1,1,1,1]
])
B = np.array([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2], 
]) 
C = np.array([
    [3, 3, 3, 3],
    [3, 3, 3, 3], 
    [3, 3, 3, 3]
])
D = np.array([
    [4, 4, 4, 4],
    [4, 4, 4, 4],
    [4, 4, 4, 4]
])

In [42]:
mat_operations(A,C)

Enter opration(+,-,*,/): /
Huhuhu.The matrices are not viable.


In [43]:
mat_operations(D, C)

Enter opration(+,-,*,/): *


array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [44]:
mat_operations(A,B)

Enter opration(+,-,*,/): -


array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

# Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".